using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InsightLab.Web.Models
{
    /// <summary>
    /// The two groups a user session can be randomly assigned to
    /// in an A/B test. Variant A is always the original/control,
    /// Variant B is always the new version being tested.
    /// </summary>
    public enum Variant
    {
        A = 0,
        B = 1
    }

    /// <summary>
    /// Represents one user/session that participated in an experiment.
    /// Many ExperimentParticipants belong to one Experiment.
    /// </summary>
    public class ExperimentParticipant
    {
        [Key]
        public int ParticipantId { get; set; }

        /// <summary>
        /// A synthetic session identifier, shown in the Data Explorer page.
        /// </summary>
        [StringLength(50)]
        public string SessionId { get; set; } = string.Empty;

        [ForeignKey(nameof(Experiment))]
        public int ExperimentId { get; set; }

        public Experiment? Experiment { get; set; }

        public Variant Variant { get; set; }

        public DateTime SessionDate { get; set; }

        /// <summary>
        /// Whether this session ended in the desired outcome
        /// (e.g. completed checkout, clicked email link, upgraded plan).
        /// </summary>
        public bool Converted { get; set; }

        /// <summary>
        /// Revenue/order value generated by this session.
        /// Only meaningful (non-zero) when Converted == true.
        /// </summary>
        [Column(TypeName = "decimal(10,2)")]
        public decimal OrderValue { get; set; }
    }
}
